#!/bin/bash

cd src
echo "build libs :"
echo "make clean"
make clean
echo "make"
make
echo "make lib"
make lib
cd ../test
echo ""
echo "build test :"
echo "make clean"
make clean
echo "make"
make
echo ""
echo "load lib..."
echo ""
echo ""
export LD_LIBRARY_PATH=../lib
echo "run test :"
./test
echo "Done."
